### ISSUE TITLE
Bug - Product Notifications error

### ISSUE THREAD

**Issue by jeking928** [potteryhouse/stock_by_attribute_1.5.3#11]
After completing an order containing more than one item with different attributes, clicking the 'ipdate' button for Product Notifications generates an error:
PHP Fatal error:  1062:Duplicate entry '180-2' for key 'PRIMARY' :: insert into products_notifications

**Comment by mc12345678** [comment]
For earlier ZC versions, the additional header_php_sba.php file has been added (this makes removing the plugin easier as little desire as there is to this) whereas more recent ZC versions include the DISTINCT "command" in the sql and no file modification is necessary (Such as in ZC 1.5.5). Closing this issue as it is/was resolved.  Latest files can be found at https://github.com/mc12345678/Stock_By_Attributes_Combined
