### ISSUE TITLE
Bug - Display of Product image in cart from SBA Selection list

### ISSUE THREAD

**Issue by potteryhouse** [potteryhouse/stock_by_attribute_1.5.3#4]
Correct the image displayed in cart when an attribute with an image is selected using the "Selection List".

Problem: The image displayed in the shopping cart is not the image of the attribute selected.

Reason, the shopping cart does not have a mechanism to save the attributes selected image. Need to determine methods to resolve this including adding more complex selection query or the possibility of adding a field to the cart supporting the attribute selection.

**Comment by mc12345678** [comment]
This has been added to the code that will be uploaded to the repository: https://github.com/mc12345678/Stock_By_Attributes_Combined at the next upload point.  Only targets the actual shopping_cart page, but will be looking to see what can/needs to be done to address other similar "pages" such as a screen drop down, etc...

Closing this issue to help clean up and address.
