### ISSUE TITLE
Investigate - Product Deleted disposition of SBA attributes

### ISSUE THREAD

**Issue by potteryhouse** [potteryhouse/stock_by_attribute_1.5.3#5]
Investigate:
What happens to attributes of a deleted product.

**Comment by mc12345678** [comment]
Have added deletion of all SBA variants for a product if the attributes of a product in the attributes controller is selected to have all attributes deleted.  This is in addition to the previous actions incorporated to delete individual option values or option names.  As far as stock control, the only thing that is removed in each of these cases currently is the stock specifically associated with the SBA variant.  The total stock of products that is tracked (or not) independently is not modified with deletion of these items.

Code is/will be provided in the version that is being maintained to support multiple versions of ZC found at: https://github.com/mc12345678/Stock_By_Attributes_Combined

Closing this issue in effort to address open items and consolidate.
