### ISSUE TITLE
Investigate - Review function zen_remove_order()

### ISSUE THREAD

**Issue by potteryhouse** [potteryhouse/stock_by_attribute_1.5.3#6]
Investigate correct functioning of:
admin/includes/functions/general.php
Look at (line 1512) the function zen_remove_order($order_id, $restock = false) {}

**Comment by mc12345678** [comment]
Believe the remove order operation has been addressed in the combined SBA software; however, the above table and data management remains something of an [open issue](https://github.com/potteryhouse/stock_by_attribute_1.5.4/issues/25) (currently tracked in the 1.5.4 version of this software) in particular the retrieval of the desired information.
